let matches = []

async function initMap() {
	const { ColorScheme } = await google.maps.importLibrary("core")
	// --- START: Constants ---
	const INITIAL_CENTER = { lat: 36.7650533, lng: -119.7995578 }; // Seems to be info booth
	const INITIAL_ZOOM = 14.2;
	const MIN_ZOOM_OFFSET = 2;
	const MAX_ZOOM_OFFSET = 3;
	const MARKER_OFFSET_FACTOR = 0.0002;
	const POPUP_PAN_PIXEL_OFFSET = 300; // Pixel offset used for panning when popup opens
	const DEFAULT_FALLBACK_IMAGE_URL = "https://towerporchfest.org/wp-content/uploads/2025/01/Untitled-1803-x-670-px1.png";
	// --- END: Constants ---

	const map = new google.maps.Map(document.getElementById("map"), {
		zoom: INITIAL_ZOOM,
		center: INITIAL_CENTER,
		mapId: "4049b264513558e3",
		minZoom: INITIAL_ZOOM - MIN_ZOOM_OFFSET,
		maxZoom: INITIAL_ZOOM + MAX_ZOOM_OFFSET,
		colorScheme: ColorScheme.DARK,
		mapTypeControl: false,
		fullscreenControl: false,
	})

	const trolleyPath = new google.maps.Polyline({
		path: [
			{lat: 36.76499756442535, 		lng: -119.79898676073246},
			{lat: 36.76493481691089, 		lng: -119.7989826567562},
			{lat: 36.76495642400253, 		lng: -119.79634088202028},
			{lat: 36.76508606642457, 		lng: -119.79633491954776},
			{lat: 36.76505957380197, 		lng: -119.79898258411826},
			{lat: 36.76499756442535, 		lng: -119.79898676073246},
			{lat: 36.76497392052814, 		lng: -119.8010560470801},
			{lat: 36.757276833053425, 	lng: -119.80104330058255},
			{lat: 36.75695599895826, 		lng: -119.80094172815676},
			{lat: 36.75673524935291, 		lng: -119.80074325330153},
			{lat: 36.75653040063636, 		lng: -119.80046655600141},
			{lat: 36.7562301419388, 		lng: -119.800289096131},
			{lat: 36.7504125518585, 		lng: -119.80036587536627},
			{lat: 36.75039926645446, 		lng: -119.80285847982687},
			{lat: 36.75063812285461, 		lng: -119.80283660334874},
			{lat: 36.75765247439101, 		lng: -119.802858812864},
			{lat: 36.7576463078158, 		lng: -119.80575299684742},
			{lat: 36.762494940188596, 	lng: -119.80578027260596},
			{lat: 36.762508871267, 			lng: -119.80456208103357},
			{lat: 36.76498699846067, 		lng: -119.80457387882751},
			{lat: 36.76498300280249, 		lng: -119.80410004432838},
			{lat: 36.7684952509903, 		lng: -119.80411777845197},
			{lat: 36.768521259690694, 	lng: -119.80105965926045},
			{lat: 36.76497392052814, 		lng: -119.8010560470801},
		],
		geodesic: true,
		strokeColor: "#FFA500",
		strokeOpacity: 0.7,
		strokeWeight: 12
	})
	
	class Popup extends google.maps.OverlayView {
		position
		containerDiv
		constructor(position, content) {
			super()
			content.classList.add("popup-bubble")

			// This zero-height div is positioned at the top of the bubble.
			const bubbleAnchor = document.createElement("div")

			bubbleAnchor.classList.add("popup-bubble-anchor")
			bubbleAnchor.appendChild(content)
			// This zero-height div is positioned at the bottom of the tip.
			this.containerDiv = document.createElement("div")
			this.containerDiv.classList.add("popup-container")
			this.containerDiv.appendChild(bubbleAnchor)
			// Optionally stop clicks, etc., from bubbling up to the map.
			Popup.preventMapHitsAndGesturesFrom(this.containerDiv)
		}
		/** Called when the popup is added to the map. */
		onAdd() {
			this.getPanes().floatPane.appendChild(this.containerDiv)
		}
		/** Called when the popup is removed from the map. */
		onRemove() {
			if (this.containerDiv.parentElement) {
				this.containerDiv.parentElement.removeChild(this.containerDiv)
			}
		}
		/** Called each frame when the popup needs to draw itself. */
		draw() {
			const divPosition = this.getProjection().fromLatLngToDivPixel(
				this.position,
			)
			// Hide the popup when it is far out of view.
			const display =
				Math.abs(divPosition.x) < 4000 && Math.abs(divPosition.y) < 4000
					? "block"
					: "none"
			if (display === "block") {
				this.containerDiv.style.left = divPosition.x + "px"
				this.containerDiv.style.top = divPosition.y + "px"
			}
			if (this.containerDiv.style.display !== display) {
				this.containerDiv.style.display = display;
			}
		}
	}

	const contentDiv = document.createElement("div");
	contentDiv.id = "content";

	const popup = new Popup(
		new google.maps.LatLng(INITIAL_CENTER.lat, INITIAL_CENTER.lng),
		contentDiv,
	)

	/**
	 * Defines all marker categories and their associated label/icon.
	 * Source of truth for:
	 *  - Legend items generated by `buildLegend()`.
	 *  - Marker icon paths assigned in `buildMarkers()`.
	 */
	const markerTypes = {
		'default': { label: 'Porch', icon: `${wpVars.themeURL}/img/map/glyph.svg` },
		'sponsored': { label: 'Sponsor', icon: `${wpVars.themeURL}/img/map/glyph-sponsor.svg` },
		'porta': { label: 'Restroom', icon: `${wpVars.themeURL}/img/map/glyph-porta.svg` },
		'info': { label: 'Info Booth', icon: `${wpVars.themeURL}/img/map/glyph-info.svg` },
		'parking': { label: 'Parking', icon: `${wpVars.themeURL}/img/map/glyph-parking.svg` },
		'vendor': { label: 'Vendor', icon: `${wpVars.themeURL}/img/map/glyph-vendor.svg` },
		'sponsored_vendor': { label: 'Sponsor & Vendor', icon: `${wpVars.themeURL}/img/map/glyph-vendor-sponsor.svg` }
	};

	let allMarkers = []
	let markerCluster

	/* --- START: Dynamic Legend --- */
	/**
	 * Populates the #map-legend element by generating list items based on
	 * the `markerTypes` object.
	 */
	function buildLegend() {
		const legendDiv = document.getElementById("map-legend");
		if (!legendDiv) return;

		const legendContent = document.createElement('div');
		legendContent.id = 'legend-content';
		const legendList = document.createElement('ul');

		Object.entries(markerTypes).forEach(([type, details]) => {
			if(type === 'sponsored_vendor')return
			const listItem = document.createElement('li');
			listItem.dataset.filterType = type;
			listItem.classList.add('is-active');

			const iconImg = document.createElement('img');
			iconImg.src = details.icon;
			iconImg.alt = details.label;
			iconImg.classList.add('legend-icon');

			const labelSpan = document.createElement('span');
			labelSpan.textContent = details.label;
			labelSpan.classList.add('legend-label');

			listItem.appendChild(iconImg);
			listItem.appendChild(labelSpan);
			legendList.appendChild(listItem);
		});

		legendContent.appendChild(legendList);
		legendDiv.innerHTML = '';
		legendDiv.appendChild(legendContent);
	}
	/* --- END: Dynamic Legend --- */

	async function buildMarkers(formData) {
		let fPorches = []
		if (markerCluster) markerCluster.clearMarkers()
		popup.setMap(null)
		allMarkers.forEach(marker => marker.marker.setMap(null))
		if (formData) {
			if(formData.show_bus){
				trolleyPath.setMap(map)
			} else if (trolleyPath) {
				trolleyPath.setMap(null)
			}
			if (formData.search) {
				const filterPerformers = wpVars.porches.filter(porch => {
					let performermatch = false
					porch.performers.map(performer => {
						if (performermatch) return
						const performerTitle = performer.performer.post_title?.toLowerCase()
						if (performerTitle) {
							if (performerTitle.includes(formData.search)) {
								performermatch = true
								if (!matches.includes(performer.performer.post_title)) {
									matches.push(performer.performer.post_title)
								}
							}
						}
					})
					return performermatch
				})
				const searched = wpVars.porches.filter(porch => formData.wp_search.some(searchPorch => porch.porch.ID === searchPorch.id))
				const combined = [...filterPerformers, ...searched]
				const deduped = Array.from(
					new Map(combined.map(porch => [porch.porch.ID, porch])).values()
				)
				fPorches = filterData(deduped, formData)
			} else {
				fPorches = filterData(wpVars.porches, formData)
			}
		} else {
			fPorches = wpVars.porches
			trolleyPath.setMap(null)
		}

		// else if(window.location.hash){
		// 	fPorches = filterData(wpVars.porches, {search: [window.location.hash.replace("#", "")]})
		// }
		const seenCoords = {}
		allMarkers = fPorches.map((porch, i) => {
			let lat = parseFloat(porch.acf.latitude)
			let lng = parseFloat(porch.acf.longitude)
			const key = `${lat.toFixed(5)},${lng.toFixed(5)}`
			if (seenCoords[key]) {
				const offset = MARKER_OFFSET_FACTOR * seenCoords[key];
				lat += Math.cos(i) * offset
				lng += Math.sin(i) * offset
				seenCoords[key]++
			} else {
				seenCoords[key] = 1
			}

			// Determine marker type string based on ACF fields
			let markerType = 'default'; // Start with default
			if (porch.acf.sponsored && porch.acf.has_food) {
				markerType = 'sponsored_vendor'
			} else if(porch.acf.sponsored){
				markerType = 'sponsored';
			} else if (porch.acf.porta_potty) {
				markerType = 'porta';
			} else if (porch.acf.info_booth) {
				markerType = 'info';
			} else if (porch.acf.parking) {
				markerType = 'parking';
			} else if (porch.acf.has_food) {
				markerType = 'vendor';
			}

			// Assign icon using the determined type and the markerTypes object
			const glyph = document.createElement("img");
			glyph.src = markerTypes[markerType].icon;

			// Assign zIndex based on type (can be expanded if needed)
			let zIndex = 1000;
			if (markerType === 'porta') {
				zIndex = 30000;
			}

			glyph.style.height = "40px";
			const marker = new google.maps.marker.AdvancedMarkerElement({
				map,
				position: { lat, lng },
				content: glyph,
				zIndex,
			})
			const imgurl = porch.img ? porch.img : DEFAULT_FALLBACK_IMAGE_URL;

			let lineup = ``
			if (porch.acf.performer_lineup) {
				porch.acf.performer_lineup.forEach((performer, i) => {
					let highlight = "initial"
					if (matches.includes(performer.performer.post_title)) {
						highlight = "#ffb6c1"
					}
					lineup += `<tr><td>${performer.start_time}</td><td style="background-color: ${highlight}"><a href="/performer/${performer.performer.post_name}">${performer.performer.post_title}</a></td></tr>`
				})
			}
			if (porch.acf.has_food) {
				lineup += `<tr><td>Vendor</td><td>${porch.acf.food_vendor.food_name}</td></tr>`
			}
			if (lineup) {
				lineup = `<div class="lineup"><table class="lineup-table"><tbody><tr><th>START TIME</th><th>PERFORMER</th></tr>${lineup}</tbody></table></div>`
			}

			marker.addListener("gmp-click", () => {
				popup.position = new google.maps.LatLng(lat, lng)
				contentDiv.innerHTML = `<div class="inner-container"><a href="${porch.link}"><h3>${porch.porch.post_title}</h3></a><img src="${imgurl}" alt="Default"><div class="header"><a href="https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}&travelmode=walking" target="_blank"><button>Get Directions!</button><a/></div>${lineup}<div class="content"><p>${porch.porch.post_content}</p></div></div>`
				const close = document.createElement("i")
				close.classList.add("fas", "fa-times-circle", "popup-close")
				contentDiv.appendChild(close)
				popup.setMap(map)
				close.addEventListener("click", () => {
					popup.setMap(null)
				})
				const newCenter = {
					lat: popup.position.lat() + POPUP_PAN_PIXEL_OFFSET / Math.pow(2, map.getZoom()),
					lng: popup.position.lng(),
				}
				map.panTo(newCenter)
			})
			return {
				marker,
				clusterable: !porch.acf.info_booth && !porch.acf.porta_potty && !porch.acf.parking
			}
		})

		const trolleyStops = [
			{lat: 36.76519733738659, 		lng: -119.79805882890179},
			{lat: 36.76469739172577, 		lng: -119.80134302791159},
			{lat: 36.762119306178015, 	lng: -119.80130066665852},
			{lat: 36.75812094163349, 		lng: -119.80132113053851},
			{lat: 36.754195136917694, 	lng: -119.80061573212695},
			{lat: 36.750676988342896, 	lng: -119.80063996251968},
			{lat: 36.7579521229005, 		lng: -119.8054374422218},
			{lat: 36.762504287017435, 	lng: -119.80424099454666},
			{lat: 36.766280784439516, 	lng: -119.80377414029049},
			{lat: 36.76821008036845, 		lng: -119.80384808424272}
		]
		trolleyMarkers = trolleyStops.map(stop=>{
			const trolleyGlyph				= document.createElement("img");
			trolleyGlyph.src 					= `${wpVars.themeURL}/img/map/glyph-bus.svg`
			trolleyGlyph.style.height = "25px"
			const trolleyMarker = new google.maps.marker.AdvancedMarkerElement({
				map,
				position: stop,
				content: trolleyGlyph,
			})
			return trolleyMarker
		})

		const clusteredMarkers = allMarkers.filter(m => m.clusterable).map(m => m.marker)
		const nonClusteredMarkers = allMarkers.filter(m => !m.clusterable).map(m => m.marker)

		const renderer = {
			render: ({ count, position }) => {
				const div = document.createElement("div");
				div.className = "custom-cluster";
				div.textContent = count;
		
				return new google.maps.marker.AdvancedMarkerElement({
					position,
					content: div,
					zIndex: 1000 + count,
				});
			}
		};
		markerCluster = new markerClusterer.MarkerClusterer({
			markers: clusteredMarkers,
			map,
			// renderer,
		})
	}
	buildMarkers()
	buildLegend()

	map.addListener("click", () => {
		popup.setMap(null)
	})

	const form = document.getElementById("map_filter")
	const search = document.getElementById("filter_search")

	form.addEventListener("submit", (e) => {
		e.preventDefault()
		matches = []
		const formData = new FormData(form)
		const values = Object.fromEntries(formData.entries())
		if (values.search) {
			fetch(`${wpVars.homeURL}/wp-json/wp/v2/porches?search=${search.value}`)
				.then(response => response.json())
				.then(data => {
					values["wp_search"] = data
					buildMarkers(values)
				})
		} else {
			buildMarkers(values)
		}
		document.getElementById("map_menu").style.display = "none"
	})
	document.getElementById("reset_filter").addEventListener("click", () => {
		form.reset()
		matches = []
		buildMarkers()
		document.getElementById("map_menu").style.display = "none"
	})
}

function filterData(data, formData) {
	hasLineup = data.filter(porch => porch.acf.performer_lineup)
	if (formData.sponsor) {
		data = data.filter(porch => porch.acf.sponsored)
	}
	if (formData.vendor) {
		data = data.filter(porch => porch.acf.has_food)
	}
	if (formData.porta) {
		data = data.filter(porch => porch.acf.porta_potty)
	}
	if(formData.now_time){
		let playingNow = []
		const rightNow = new Date()
		// rightNow.setHours(17, 0, 0, 0) // Set to 2:00 PM for testing
		const THIRTY_MINUTES = 30 * 60 * 1000
		const thirtyOutDate = new Date(rightNow.getTime() + THIRTY_MINUTES)

		if (hasLineup.length != 0) {
			hasLineup.forEach(porch => {
				let bool = false
					porch.acf.performer_lineup.forEach(performer => {
						if (bool) return
						const [startTime, startModifier] = performer.start_time.trim().split(" ");
						[startHours, startMinutes] = startTime.split(":").map(Number)
						if (startModifier === "pm" && startHours !== 12) startHours += 12
						if (startModifier === "am" && startHours === 12) startHours = 0
						const starts = new Date(rightNow.getFullYear(), rightNow.getMonth(), rightNow.getDate(), startHours, startMinutes, 0, 0)
						const [endTime, endModifier] = performer.end_time.trim().split(" ");
						[endHours, endMinutes] = endTime.split(":").map(Number)
						if (endModifier === "pm" && endHours !== 12) endHours += 12
						if (endModifier === "am" && endHours === 12) endHours = 0
						const ends = new Date(rightNow.getFullYear(), rightNow.getMonth(), rightNow.getDate(), endHours, endMinutes, 0, 0)
						const isPlayingNow = (ends >= rightNow && ends <= thirtyOutDate) || (starts >= rightNow && starts <= thirtyOutDate)
						if(isPlayingNow){
							bool = true
							if (!matches.includes(performer.performer.post_title)) {
								matches.push(performer.performer.post_title)
							}
						}
					})
					if (bool) {
						playingNow.push(porch)
					}
				})
			data = playingNow
		}
	}
	if (formData.time) {
		let afterTime = []
		if (hasLineup.length != 0) {
			hasLineup.forEach(porch => {
				let bool = false
				porch.acf.performer_lineup.forEach(performer => {
					if (bool) return
					let [hours, minutes] = formData.time.split(':').map(Number)
					const now = new Date()
					const formDate = new Date(now.getFullYear(), now.getMonth(), now.getDate(), hours, minutes, 0, 0)
					const [time, modifier] = performer.start_time.trim().split(" ");
					[hours, minutes] = time.split(":").map(Number)
					if (modifier === "pm" && hours !== 12) hours += 12
					if (modifier === "am" && hours === 12) hours = 0
					const performanceDate = new Date(now.getFullYear(), now.getMonth(), now.getDate(), hours, minutes, 0, 0)
					if (formDate <= performanceDate) {
						bool = true
					}
				})
				if (bool) {
					afterTime.push(porch)
				}
			})
			data = afterTime
		}
	}
	if (formData.genre != "none") {
		let hasGenre = []
		if (hasLineup.length != 0) {
			hasLineup.forEach(porch => {
				let bool = false
				porch.performers.forEach(performer => {
					if (bool) return
					if (performer.genres) {
						if (performer.genres.filter(genre => genre == formData.genre).length != 0) {
							if (!matches.includes(performer.performer.post_title)) {
								matches.push(performer.performer.post_title)
							}
							bool = true
						}
					}
				})
				if (bool) {
					hasGenre.push(porch)
				}
			})
			data = hasGenre
		}
	}
	return data
}

const menu = document.getElementById("map_menu")
document.getElementById("map_menu_btn").addEventListener("click", () => {
	menu.style.display = "block"
})
document.getElementById("close_menu").addEventListener("click", () => {
	menu.style.display = "none"
})

window.addEventListener('resize', setVhUnit)

function setVhUnit() {
	const vh = window.innerHeight * 0.01;
	document.documentElement.style.setProperty('--vh', `${vh}px`)
}
setVhUnit()